version: '3'


services:
  nginx:
    network_mode: "host"
    build: ./compose/local/nginx
    container_name: nginx
    volumes:
      - ./media/:/usr/media/
      # - ./nginxlogs/:/var/log/nginx # incase we need errors and access logs saved on host
